import fs from "fs";

const catalog = JSON.parse(fs.readFileSync("themes.json", "utf8"));
const payload = {
  defaultTheme: catalog.defaultTheme,
  themes: catalog.themes,
};

const js =
  "// Generated by build.mjs from themes.json\n" +
  "window.ABYSS_THEME_CATALOG = " +
  JSON.stringify(payload, null, 2) +
  ";\n";

fs.writeFileSync("themes-data.js", js);
console.log(`Wrote themes-data.js (${payload.themes.length} themes)`);
