import crypto from "crypto";
import fs from "fs";

const catalog = JSON.parse(fs.readFileSync("themes.json", "utf8"));
const payload = {
  defaultTheme: catalog.defaultTheme,
  themes: catalog.themes,
};

const js =
  "// Generated by build.mjs from themes.json\n" +
  "window.ABYSS_THEME_CATALOG = " +
  JSON.stringify(payload, null, 2) +
  ";\n";

fs.writeFileSync("themes-data.js", js);

const stamp = crypto
  .createHash("sha256")
  .update(fs.readFileSync("themes.json"))
  .digest("hex")
  .slice(0, 8);

const indexPath = "index.html";
let index = fs.readFileSync(indexPath, "utf8");
index = index.replace(
  /(href="preview\.css)(?:\?v=[^"]*)?(")/,
  `$1?v=${stamp}$2`
);
index = index.replace(
  /(src="themes-data\.js)(?:\?v=[^"]*)?(")/,
  `$1?v=${stamp}$2`
);
index = index.replace(
  /(src="preview\.js)(?:\?v=[^"]*)?(")/,
  `$1?v=${stamp}$2`
);
fs.writeFileSync(indexPath, index);

console.log(`Wrote themes-data.js (${payload.themes.length} themes), asset ?v=${stamp}`);
